# Generated by Django 2.2.2 on 2019-07-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('slug', models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='PagesPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('price', models.CharField(blank=True, max_length=64, null=True, verbose_name='Price')),
                ('token', models.IntegerField(null=True, verbose_name='Token')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('slug', models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='Subscription ends')),
                ('order_id', models.CharField(blank=True, max_length=150, verbose_name='Order id')),
                ('bonus', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rompas.Subscription', verbose_name='Subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('you_tube', models.URLField(blank=True, null=True, verbose_name='You_Tube')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Size')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Main Photo')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Old Price')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rompas.Category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rompas.Product', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rompas.MainCategory', verbose_name='Main Category'),
        ),
        migrations.CreateModel(
            name='BuyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rompas.Product', verbose_name='Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BuyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Data')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rompas.Product', verbose_name='Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('slug', models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('main_text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Main Text')),
                ('photo_one', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo One')),
                ('photo_two', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo Two')),
                ('photo_three', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo Three')),
                ('photo_four', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo Four')),
                ('photo_five', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo Five')),
                ('main_page', models.URLField(blank=True, null=True, verbose_name='Main Page')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rompas.ArticleCategory', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
