# Generated by Django 2.2.2 on 2019-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0002_auto_20190731_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug'),
        ),
    ]
