# Generated by Django 2.2.2 on 2019-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0004_auto_20190801_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesphoto',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagesphoto',
            name='right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagesphoto',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
