# Generated by Django 2.2.2 on 2019-08-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0005_auto_20190801_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
