# Generated by Django 2.2.2 on 2019-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0006_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug'),
        ),
    ]
