# Generated by Django 2.2.2 on 2019-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0007_auto_20190801_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens_left',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tokens Left'),
        ),
    ]
