# Generated by Django 2.2.2 on 2019-08-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0009_profile_email_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyhistory',
            name='data',
        ),
        migrations.DeleteModel(
            name='BuyList',
        ),
    ]
