# Generated by Django 2.2.2 on 2019-08-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0010_auto_20190802_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyhistory',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Purchased at'),
        ),
    ]
