# Generated by Django 2.2.2 on 2019-08-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0011_buyhistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=64, null=True, verbose_name='Email')),
                ('message', models.TextField(max_length=2000, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
