# Generated by Django 2.2.2 on 2019-08-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0012_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tokens ends'),
        ),
    ]
