# Generated by Django 2.2.2 on 2019-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0013_profile_tokens_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_active',
            field=models.BooleanField(default=False, verbose_name='Subscription active'),
        ),
    ]
