# Generated by Django 2.2.2 on 2019-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0014_profile_subscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sybmol'),
        ),
    ]
