# Generated by Django 2.2.2 on 2019-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0017_remove_profile_can_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name Slug'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.CharField(blank=True, help_text="Don't touch it!", max_length=150, verbose_name='Slug'),
        ),
    ]
