# Generated by Django 2.2.2 on 2019-08-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0018_auto_20190809_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name_slug',
            new_name='name',
        ),
    ]
