# Generated by Django 2.2.2 on 2019-10-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0020_auto_20191003_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(upload_to='', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
