# Generated by Django 2.2.2 on 2019-11-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0021_auto_20191003_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description Ru'),
        ),
        migrations.AddField(
            model_name='article',
            name='main_text_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Main Text Ru'),
        ),
        migrations.AddField(
            model_name='article',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name Ru'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name Ru'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name Ru'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='description_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description Ru'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name Ru'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description Ru'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name Ru'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name Ru'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name Ru'),
        ),
    ]
