# Generated by Django 2.2.2 on 2019-12-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0022_auto_20191124_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='you_tube',
            field=models.URLField(blank=True, null=True, verbose_name='You_Tube, Only Assets'),
        ),
    ]
