# Generated by Django 2.2.2 on 2020-04-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0027_auto_20200406_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order_id',
        ),
    ]
