# Generated by Django 2.2.2 on 2020-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0028_remove_profile_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Description')),
            ],
        ),
    ]
