# Generated by Django 2.2.2 on 2020-04-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0029_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
    ]
