# Generated by Django 2.2.2 on 2020-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0030_tokens_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesphoto',
            name='photo_ru',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
