# Generated by Django 2.2.2 on 2020-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0031_pagesphoto_photo_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='photo_ru',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo Ru'),
        ),
        migrations.AlterField(
            model_name='pagesphoto',
            name='photo_ru',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo ru'),
        ),
    ]
