# Generated by Django 2.2.2 on 2020-04-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0032_auto_20200429_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Name Ru'),
        ),
    ]
