# Generated by Django 2.2.2 on 2020-04-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rompas', '0027_auto_20200406_0932'),
        ('orders', '0003_auto_20200413_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_subscription', to='rompas.Subscription'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='rompas.Product'),
        ),
    ]
