# Generated by Django 2.2.2 on 2020-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tokens',
            field=models.BooleanField(default=False),
        ),
    ]
